# Generated by Django 3.2.5 on 2021-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
