# Generated by Django 3.2.5 on 2021-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reciperequirement_ingredient_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient_cost',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
