# Generated by Django 3.2.5 on 2021-07-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_reciperequirement_ingredient_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient_cost',
        ),
    ]
