# Generated by Django 3.2.5 on 2021-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_reciperequirement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=3),
        ),
    ]
